### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mxstbr** [pure-ui/styleguide#12]
**Development Alpha**

- [x] Get all components into the client and render them
- [x] Navigation
- [x] PropTypes parsing
- [x] Display meta informations
- [x] Load components on demand and not on first load
- [x] Examples
- [x] Flow parsing
- [x] Fuzz testing by adding react-pure-ui to the client
  - [x] Primitives
  - [x] Arrays
  - [x] Objects
  - [x] Nested Arrays
  - [x] EnumControl
  - [x] make sure it doesn't break without proptypes
  - [x] union types (Flow)
  - [x] oneOfType (Proptypes)
  - [ ] custom class (Flow)
  - [ ] custom class (Proptypes)
  - [ ] Normalize
  - [x] add tests
  - [x] Nested Objects
  - [ ] Custom propTypes with custom controls (e.g. ImmutableJS)
  - [x] handle isRequired
  - [x] make number a number control instead of integer
  - [x] add option to define integer control (via comments?)
- [x] Component Testing with chai-enzyme
- [ ] Homepage
- [ ] Documentation

**Design**

- [x] Name (https://github.com/pure-ui/react-pure-ui/issues/3)
- [ ] Logo
- [x] Styleguide Client
- [ ] *Marketing Website*

**Future**

- [ ] Relay parsing
- [ ] *Chrome Plugin/JS Snippet*
- [ ] Warn for common performance pitfalls in components. (e.g. warn if defined propTypes contain only primative values and if pure render isn't applied)
- [ ] Render compilation errors in a heads up display like figwheel (see [here at 18:00](http://youtu.be/j-kj2qwJa_E))

**Comment by nikgraf** [comment]
Things up for discussion:

- allow to overwrite the Page component so people can customise it
- generate various states based on comments examples/fixtures data (How does it work with ImmutableJS?)

**Comment by nikgraf** [comment]
I updated the Roadme to be split in Alpha dev & later

**Comment by mxstbr** [comment]
Closing as the remaining points were split across multiple issues.
